# This is a basic workflow to help you get started with Actions

name: training1-chapter2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dummy" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  date1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: date

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          touch ubuntu.txt
  date2:
    runs-on: windows-latest
    steps:
    - run: Get-Date

  date3:
    runs-on: macos-latest
    steps:
    - run: |
        date
        touch macos.txt
        ls -las

  date4:
    runs-on: ubuntu-latest
    needs: [date1,date2,date3]
    steps:
    - run: |
        date
        ls -las
  
