name: Workflow dispatch

on:
#   pull_request:
#     branches: ['*']
#     # types:
#     #   - closed
#   push:
#     branches: ['*']
  workflow_dispatch:
  workflow_call:

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT | jq .

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List
        # Any job referencing the environment will not run until at least one reviewer approves the job.
        # environment: production
        run: |
          echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          echo GITHUB_SHA=$GITHUB_SHA
          echo GITHUB_REF=$GITHUB_REF
          ls -las
          find ./ -type f -maxdepth 1 -exec echo {} \;  -exec cat {} \; -exec echo \;
          git log -3

      - name: Fail
        run: false