name: Artifact test

on:
  push:
    branches: ['*']

jobs:
  list:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List
        run: |
          ls -las
          find ./ -type f -maxdepth 1 -exec echo {} \;  -exec cat {} \; -exec echo \;
          git log -3